FROM {{ web_image }}:{{ awx_version }}
USER 0
RUN sudo dnf -y remove nginx
ADD launch_awx_task.sh /usr/bin/launch_awx_task.sh
ADD supervisor_task.conf /etc/supervisord.conf
USER 1000
EXPOSE 8052
CMD /usr/bin/launch_awx_task.sh
